apiVersion: personal-iot.mgrote/v1alpha1
kind: Location
metadata:
  labels:
    app.kubernetes.io/name: location
    app.kubernetes.io/instance: location-sample
    app.kubernetes.io/part-of: 4
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: 4
  name: location-sample
spec:
  # TODO(user): Add fields here
