apiVersion: personal-iot.mgrote/v1alpha1
kind: Poweroutlet
metadata:
  labels:
    app.kubernetes.io/name: poweroutlet
    app.kubernetes.io/instance: poweroutlet-sample
    app.kubernetes.io/part-of: 4
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: 4
  name: poweroutlet-sample
spec:
  # TODO(user): Add fields here
